### ISSUE TITLE
Unable to import AsyncClient

### ISSUE THREAD

**Issue by cboothe** [osiset/basic_shopify_api#2]
Python 3.7.9

File "./main.py", line 2, in <module>
    from basic_shopify_api import Session, Options, AsyncClient
  File "/usr/local/lib/python3.7/site-packages/basic_shopify_api/__init__.py", line 3, in <module>
    from .clients import Client, AsyncClient, ApiCommon
ModuleNotFoundError: No module named 'basic_shopify_api.clients'

**Comment by osiset** [comment]
Odd, I'll have to find out whats on the go there.

**Comment by cboothe** [comment]
Looks like a PIP version issue.
The pip version is 

# Current version of libary
VERSION = "0.1.1"

When I used the module directly from the repo it says version is 
VERSION = "0.1.2"

**Comment by osiset** [comment]
![image](https://user-images.githubusercontent.com/2420282/103290481-3b2aa400-49c4-11eb-9833-f7a73447242c.png)

Not sure what could be the issue here.

**Comment by cboothe** [comment]
My pip3 is linked to version pip 20.0.2

That is all I can think of.
