### ISSUE TITLE
Public access does not authenticate

### ISSUE THREAD

**Issue by jaddison** [osiset/basic_shopify_api#3]
```
    shopify_pkey = "shpss_bbabbbabb"
    auth_token = "shpat_aaaaaaaa"

    opts = Options()
    sess = Session(domain=shopOrigin, password=auth_token, secret=shopify_pkey)
    async with AsyncClient(sess, opts) as client:
        shop = await client.rest("get", "/admin/api/shop.json")
        print(shop.body, shop.status)
```

Based on https://shopify.dev/tutorials/authenticate-with-oauth#step-4-making-authenticated-requests, the `auth_token` from above should be placed into the `X-Shopify-Access-Token` header, but it is not. It looks like from the code that only 'private' mode uses that header:
```
        if self.options.is_private:
            headers = {ACCESS_TOKEN_HEADER: self.session.password, **headers}
        return {**self.options.headers, **headers}
```

I think that's backwards, shouldn't public be using the header, based on what I read in their docs?

If I manually use my key in that header (via curl or Insomnia), it functions as expected.

**Comment by jaddison** [comment]
Confirmed: it works if I [change these lines](https://github.com/osiset/basic_shopify_api/blob/master/basic_shopify_api/clients/common.py#L105-L107) to:
```
        if self.options.is_public:
            headers = {ACCESS_TOKEN_HEADER: self.session.password, **headers}
        return {**self.options.headers, **headers}
```

(`is_private` -> `is_public`)

**Comment by osiset** [comment]
I believe you're correct. I will adjust.

**Comment by osiset** [comment]
1.0.0 addresses this, thanks.
